{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  secretName: {{ .Values.certificate.name }}
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
  - {{ .Values.certificate.commonName }}
  issuerRef:
    name: {{ .Values.certificate.issuer.name }}
    kind: {{ default "ClusterIssuer" .Values.certificate.issuer.kind }}
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 2160h # 90d
  renewBefore: 720h # 30d
{{- end }}
