apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-terraform-mcp-svc
  labels:
    app: {{ include "terraform-mcp.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "terraform-mcp.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
