{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hashicorp-mcp.fullname" . }}-ingress
  labels:
    {{- include "hashicorp-mcp.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      {{- if index .Values "terraform-mcp" "enabled" }}
      - path: {{ index .Values "terraform-mcp" "path" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "hashicorp-mcp.fullname" . }}-terraform-mcp-svc
            port:
              number: {{ index .Values "terraform-mcp" "service" "port" | default 80 }}
      {{- end }}
      {{- if index .Values "vault-mcp" "enabled" }}
      - path: {{ index .Values "vault-mcp" "path" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "hashicorp-mcp.fullname" . }}-vault-mcp-svc
            port:
              number: {{ index .Values "vault-mcp" "service" "port" | default 80 }}
      {{- end }}
{{- end }}
