name: Release Helm Charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure Git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run Vault chart-releaser job
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts/vault-mcp
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true # Skip charts that have already been released
      - name: Run Terraform chart-releaser job
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts/terraform-mcp
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true # Skip charts that have already been released
      - name: Run parent chart-releaser job
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts/hashicorp-mcp
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true # Skip charts that have already been released

